name: distance-app-prototype

services:
  ui-app:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
  api-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: node build/app.js
    expose:
      - "4000"
    ports:
      - "4000"
